# Use a basic Python image
FROM python:3.8

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Run a simple Python script when the container launches
CMD ["python", "src/predict.py"]
